### ISSUE TITLE
Line 130 errors while dumping blobs on Windows 10

### ISSUE THREAD

**Issue by homeffod-github** [RossDarker/A5-A6X-Blobs-Dumper#4]
When trying to dump blobs using ./dumpblobs, I get line 130: 20XX Segmentation Fault errors, and then FATAL: cannot open myblob.plist, followed by the Did NOT Succeed error.

- Model: Phone4,1
- iOS Version: 7.1

**Desktop I are using these scripts on:**
 - OS: Windows
 - Version: 10 21H2

https://pastebin.com/YAPZzktg

**Comment by RossDarker** [comment]
So far I haven't found a direct solution to this, but it appears to be a problem with shshdump.exe, for certain device-iOS pairs.

Some of the things I've tried are:
• Creating ipsw without -memory
• Using only one ipsw, and using the corresponding firmware bundle, for the iOS currently on the device
• Using cmd for certain parts
• Using alternative ways to enter kDFU mode
• Letting shshdump.exe send the pwnediBEC, instead of the user

Nothing here or any of the combinations have worked, and all I've found is that other people have said shshdump.exe is broken, which is what this tool uses for Windows, since the Windows version of irecovery doesn't have a -g option.

I have had shshdump.exe (and so this tool on Windows) work just fine on certain device-iOS pairs, but just not work on others - resulting in the 0 byte blob dump. 

The workaround was to use a macOS VM or attempt to boot into macOS on a PC. People have had success with this. It's not ideal, and obviously not a direct fix, however, that may be the only way to get this running on a PC currently.
