### ISSUE TITLE
Can't use ./prepare script

### ISSUE THREAD

**Issue by b1sby** [RossDarker/A5-A6X-Blobs-Dumper#5]
**Describe the problem:**
Can't use ./prepare script.

**iOS Device you're attempting to dump blobs from:**
iPhone5,4 (5c Global)
iOS 7.0 (11A466)

**Desktop you are using these scripts on:**
macOS 10.12.6 Sierra

**Screenshots:**
![help](https://user-images.githubusercontent.com/108209872/200693572-61fd5e2d-bdab-4555-9d17-35c6e34a63c2.png)

**Additional context:**
trying to dump blobs from my iphone so i can safely update

**Comment by RossDarker** [comment]
I've updated the Troubleshooting page with clearer instructions on how to resolve this. I tested the solution on OS X Mavericks, which is older than Sierra, so it should apply there too - do report back, thanks.

**Comment by b1sby** [comment]
Hello, I have tried this on Catalina after a while and it still doesn't seem to work. I'm thinking it might not be requesting 11a466 (5c/5s) but instead it could be requesting 11a465 (other devices) instead of an issue with curl . If I am wrong about the request of 11a465, do you know of another possible method I could use for my phone. 

Thanks
-b1sby
![Screenshot 2023-01-31 at 23 50 21](https://user-images.githubusercontent.com/108209872/215909935-41b843bd-6db5-47fe-b015-a9793d476681.png)

**Comment by RossDarker** [comment]
This turned out to be two issues in one, the first of which (SSL peer handshake failed) is fixed by using the newer version of curl, in your case from running Catalina.

The second point, I can see why it’s going wrong. If you check [https://ipsw.me/iPhone5,4](https://ipsw.me/iPhone5,4)  you’ll notice that 7.0.1 is listed as the first iOS version, and I’m using the ipsw.me API to calculate BuildID’s and fetch IPSW’s from Apple. So that’s why it’s not finding it. Obviously 7.0 does exist for this model, as you’re running it and it’s listed here [https://www.theiphonewiki.com/wiki/Firmware/iPhone/7.x](https://www.theiphonewiki.com/wiki/Firmware/iPhone/7.x) 

This is also the case with iPhone5,3 and iOS 7.0
As far as I know, the other devices on ipsw.me show all the available firmware, and this is a very specific case so it makes sense why it took a while to show up.

Should be a simple fix, I’ll get to it pretty soon.

**Comment by RossDarker** [comment]
I've changed (again) how the Build ID is found from the iOS version, as well as tidying some things up.
This is much better than previously, but still uses ipsw.me's API, so I've created an exception file in order to locate iOS 7.0 for iPhone5,4 and 5,3.
Should there be other devices in the future that don't have specific firmware on ipsw.me, I can add them to this exception file. 

This is all done automatically though, and you can use these scripts just as before.
Report back again, then I'll close the issue if all works out.
Thanks
